### ISSUE TITLE
Improvement list for PR#797

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#887]
Although #797 has merged, there are still some points need to improve:

- [x] How to set dlm options safely, eg. some nodes are quorate, some are not. Agree, it is a transient corner case.
- [x] Check if corosync-qdevice already started when starting cluster #898 
- [x] Do action to corosync-qdevice even if it's not configured #895 
- [x] Cover all cases when standby node for other valid boolean values "false/no/n/0" #893 
- [x] pre stop check/behavior? #900 
- [x] When has node shutdown, how to start/stop other available nodes? #896
