### ISSUE TITLE
One liner plan

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/crmsh#942]
- [x] One liner to create a HA cluster inside container #957 
- [x] One liner to do the unit test #940
- [x] One liner to do the functional test #957
